name: Test

on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.4.0
      
    - name: Build the test Docker image
      run: docker build --tag wait-for .
      
    - name: Run the tests
      run: docker run --tty wait-for

  release:
    name: Release
    runs-on: ubuntu-20.04

    needs:
      - test

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
